config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'master#index'
  # get 'master/index'
  get 'master/new'
  get 'master/:id' => 'master#show', as: 'master_show'
  get 'master/:id/edit' => 'master#edit', as: 'master_edit'
  get 'users/index'
  get 'users/:id' => 'users#details', as: 'users_details'
  post 'movies' => 'master#create'
  patch 'master/:id' => 'master#update', as: 'master_update'
  delete 'master/:id' => 'master#destroy', as: 'master_destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/master_controller.rb
class MasterController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to root_path
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :impression, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def details
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/head_helper.rb
module HeadHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/master_helper.rb
module MasterHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>KinoCritic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'master/header' %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/master/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'KinoCritic', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Show Movie Reviews', root_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Write a Review', master_new_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'View Users', users_index_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Sign Out?" }, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In',  new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/master/edit.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <%= form_with model: @movie, url: master_update_path(@movie.id), method: :patch do |f| %>
      <h5 class="card-title">
        <%= f.text_field :title %>
      </h5>
      <p class="card-text">
        <%= f.text_area :impression %>
      </p>
      <%= f.submit class:"btn btn-secondary"%>
    <% end %>
  </div>
</div>

app/views/master/index.html.erb
<h1>Movie List</h1>
<br/>

<table class="table table-striped table-hover table-bordered border-secondary">
    <thead class="table-dark">
        <tr>
            <th><h2>Title</h2></th>
            <th><h2>Impression</h2></th>
            <th><h2>User Id</h2></th>
        </tr>
    </thead>
    <tbody>
        <% @movies.each do |movie| %>
        <tr>
            <td>
                <%= link_to movie.title, master_show_path(movie.id) %>
            </td>
            <td>
                <%= movie.impression %>
            </td>
            <td>
                <%= movie.user_id %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<% if user_signed_in? %>
    <br/>
    <%= link_to 'Write a Review', master_new_path, class:"btn btn-secondary" %>
<% end %>

app/views/master/new.html.erb
<div class="card" style="width: 18rem;">
  <div class ="card-body">
    <%= form_with model: @movie do |f| %>
      <h5 class="card-title">
        <%= f.text_field :title, placeholder:"Title" %>
      </h5>
      <p class="card-text">
        <%= f.text_area :impression, placeholder:"Impression" %>
      </p>
      <p class="card-text">
        <%= f.number_field :user_id, id: :movie_user_id, value: current_user.id, type: :hidden %>
      </p>
      <%= f.submit class:"btn btn-secondary"%>
    <% end %>
  </div>
</div>

app/views/master/show.html.erb
<div class="card" style="width: 18rem;">
    <div class ="card-body">
        <h5 class="card-title">
            <%= @movie.title %>
        </h5>
        <p class="card-text">
            <%= @movie.impression %>
        </p>
    </div>
    <% if user_signed_in? %>
        <div class="card-body">
            <%= link_to 'Edit', master_edit_path, class:"btn btn-secondary" %>
            <%= link_to 'Delete', master_destroy_path(@movie.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure about that?" }, class:"btn btn-secondary" %>
        </div>
    <% else %>
        <div class="card-body">
            <%= link_to 'Back', root_path, class:"btn btn-dark" %>
        </div>
    <% end %>
</div>

app/views/users/details.html.erb
<h1>Details</h1>
<br/>

<div class="card" style="width: 18rem;">
    <div class ="card-body">
        <h5 class="card-title">
            Username: <%= @user.username %>
        </h5>
        <p class="card-text">
            Email Address: <%= @user.email %>
        </p>
    </div>
    <div class="card-body">
        <%= link_to 'Back', users_index_path, class:"btn btn-dark" %>
    </div>
</div>

app/views/users/index.html.erb
<h1>User Index</h1>
<br/>

<table class="table table-striped table-hover table-bordered border-secondary">
    <thead class="table-dark">
        <tr>
            <th><h2>Username</h2></th>
            <th><h2>Contact Email</h2></th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td>
                <%= link_to user.username, users_details_path(user.id) %>
            </td>
            <td>
                <%= user.email %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class:"btn btn-dark btn-sm" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class:"btn btn-dark btn-sm" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class:"btn btn-dark btn-sm" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>